### ISSUE TITLE
Consultar existencia producto

### ISSUE THREAD

**Issue by sebasarangom** [sebasarangom/ccpArquitecturasAgiles#1]
Como vendedor, cuando seleccione la opción de consultar la existencia de un producto en bodega a través de la aplicación móvil, dado que el sistema opera normalmente, espero que el sistema esté 99.99% disponible para conocer la categoría del producto, su ubicación y la cantidad de ese producto en cada una de las bodegas de un país al momento de realizar cada consulta.

> Actualización de HA:
Como vendedor, cuando seleccione la opción de consultar la existencia de un producto en bodega a través de la aplicación móvil, dado que el sistema opera normalmente, quiero conocer la categoría del producto, su ubicación y la cantidad de ese producto en cada una de las bodegas de un país. Esta funcionalidad debe estar disponible el 99.99% del tiempo.

**Comment by japereza** [comment]
La redaccion es confusa: COMO... CUANDO.. DADO... ESPERO (Esto es la respuesta al estimulo), ESTO OCURRE /SUCEDE ( es la medida de la respuesta no respuesta)

**Comment by sebasarangom** [comment]
Se actualiza la HA, incorporando los escenarios de calidad mediante narrativa, según la estructura dada.

**Comment by sebasarangom** [comment]
Se cierra al terminar el sprint 1.
