### ISSUE TITLE
Garantizar la identidad de los usuarios

### ISSUE THREAD

**Issue by ctovarb** [sebasarangom/ccpArquitecturasAgiles#10]
Como vendedor, cuando requiera iniciar sesión con mi cuenta dado que el sistema opera normalmente quiero garantizar mi identidad en la aplicación para poder poder realizar operaciones críticas. Esta funcionalidad debe operar el 99.9% del tiempo

**Comment by japereza** [comment]
Bien redactado: es clara la respuesta y la medida de la respuesta

**Comment by sebasarangom** [comment]
Se cierra al terminar el sprint 1.
