### ISSUE TITLE
Actualizacion estado de cuenta del cliente

### ISSUE THREAD

**Issue by sriveros21** [sebasarangom/ccpArquitecturasAgiles#11]
Como distribuidor y operario de logistica, cuando vaya a realizar la entrega de productos y el sistema este operando en condiciones normales, el sistema debe tener disponibilidad del estado de cuenta del cliente en un 99.99%  para poder realizar consultas de su estado de cuenta.

**Comment by japereza** [comment]
OJO seria una historia por cada usuario. Cada uno puede generar el estimulo independiente del otro.

**Comment by sebasarangom** [comment]
Se cierra al terminar el sprint 1.
