### ISSUE TITLE
Actualizacion estado de cuenta del cliente con poca disponibilidad

### ISSUE THREAD

**Issue by sriveros21** [sebasarangom/ccpArquitecturasAgiles#12]
Como distribuidor y operario de logistica, cuando vaya a realizar la entrega de productos y el sistema este operando sin conexion al sistema de alertas para el estado de cuenta, el sistema debe continuar disponible para el usuario mostrando la ultima informacion mas reciente ingresada al sistema y mostrando un mensaje al usuario del tiempo que lleva desconectado del sistema de alertas, una vez se reestablezca la conexion debe informar de nuevo al usuario la actualizacion de la informacion y actualizar el 100% de los estados de cuenta de los clientes.

**Comment by japereza** [comment]
OJO seria una historia por cada usuario por que cada uno independiete puede generar el estimulo y no se requiere que los dos generen el estimulo al tiempo.

La redaccion es confusa: COMO... CUANDO.. DADO... ESPERO (Esto es la respuesta al estimulo), ESTO OCURRE /SUCEDE ( es la medida de la respuesta no respuesta)

**Comment by sebasarangom** [comment]
Se cierra al terminar el sprint 1.
