### ISSUE TITLE
Operacion del movil fuera de linea

### ISSUE THREAD

**Issue by sriveros21** [sebasarangom/ccpArquitecturasAgiles#13]
Como distribuidor y operario de logistica, cuando quisiera registrar información en la aplicación móvil y se presentan fallas en las comunicaciones, la aplicación movil debe seguir teniendo una disponibilidad del 99.99% e ir almacenando los cambios localmente y una vez tenga de nuevo señal de internet enviará la información a la base de datos del sistema y estare disponible para el resto de los servicios, la aplicación movil debe consultar de forma automatica el estado de la red cada 2 segundos y guardar la información de forma temporal si no presenta conexión, una vez se establezca conexión debe iniciar el envío de la información en 5 segundos.

**Comment by japereza** [comment]
OJO seria una historia por cada usuario. Cada uno puede generar el estimulo independiente del otro.

La redaccion es confusa: COMO... CUANDO.. DADO... ESPERO (Esto es la respuesta al estimulo), ESTO OCURRE /SUCEDE ( es la medida de la respuesta no respuesta)

**Comment by sebasarangom** [comment]
Se cierra al terminar el sprint 1.
