### ISSUE TITLE
Registrar nueva orden de compra

### ISSUE THREAD

**Issue by sebasarangom** [sebasarangom/ccpArquitecturasAgiles#2]
Como vendedor, cuando quiera registrar una nueva orden de compra, dado que el sistema opera normalmente, espero que el sistema esté 99.95% disponible durante la jornada de 6am a 8pm, para realizar la validación de si es posible realizar la compra consultando el número de unidades disponibles del producto en negociación y retornar la fecha estimada de entrega para coordinarla con el cliente.

> Actualización de HA:
Como vendedor, cuando quiera registrar una nueva orden de compra, dado que el sistema opera normalmente, quiero poder realizar la validación de si es posible realizar la compra consultando el número de unidades disponibles del producto en negociación y retornar la fecha estimada de entrega para coordinarla con el cliente. Esta funcionalidad debe estar disponible el 99.95% del tiempo durante la jornada laboral de 8am a 6pm.

**Comment by japereza** [comment]
La redaccion es confusa: COMO... CUANDO.. DADO... ESPERO (Esto es la respuesta al estimulo), ESTO OCURRE /SUCEDE ( es la medida de la respuesta no respuesta)

**Comment by sebasarangom** [comment]
Se actualiza la HA, incorporando los escenarios de calidad mediante narrativa, según la estructura dada.

**Comment by sebasarangom** [comment]
Se cierra al terminar el sprint 1.
