### ISSUE TITLE
Entrega de un pedido

### ISSUE THREAD

**Issue by sebasarangom** [sebasarangom/ccpArquitecturasAgiles#3]
Como distribuidor y operario de logística, cuando esté en camino a la entrega de un pedido y el sistema presente indisponibilidad por problemas de conexión a internet, espero que el sistema me notifique la última vez que realizó el último recálculo y alerta de ruta, y esté realizando un intento de reconexión cada 2 segundos hasta tener la aplicación nuevamente con una disponibilidad del 99.0% y, una vez sea reestablecida la conexión, notificar al distribuidor y operario de logística.

**Comment by japereza** [comment]
Es disponibilidad pero debe mejorar la redaccion para que sea rapidamente entendible por un stakeholder

**Comment by sebasarangom** [comment]
Se cierra al terminar el sprint 1.
