### ISSUE TITLE
Cálculo de Ruta Optima de Camión

### ISSUE THREAD

**Issue by Helena-Pat29** [sebasarangom/ccpArquitecturasAgiles#4]
Como gestor de entregas, cuando seleccione la opción de generar una ruta óptima de un camión, dado que el sistema opera normalmente, quiero ver el detalle del recorrido del camión en el cual se especifica el recorrido y tiempos para poder entregar la información de la ruta óptima al conductor del camión asignado a la ruta de entregas. El sistema debe responder al 99.0% de las  peticiones de calculo de ruta optima.

**Comment by japereza** [comment]
Bien redactada: es claro que es la respuesta y que es la medida de la respuesta

**Comment by sebasarangom** [comment]
Se cierra al terminar el sprint 1.
