### ISSUE TITLE
Consulta inventario producto desde App Movil

### ISSUE THREAD

**Issue by Helena-Pat29** [sebasarangom/ccpArquitecturasAgiles#6]
Como Administrador de Compras, cuando seleccione la opción de ver el inventario de un producto desde la app móvil, dado que el sistema opera normalmente, quiero ver las cantidades de productos disponibles y su respectiva ubicación para poder definir si se requiere generar ordenes de compra. El sistema debe responder al 99.9% de estas peticiones.

**Comment by japereza** [comment]
La redaccion es confusa: COMO... CUANDO.. DADO... ESPERO (Esto es la respuesta al estimulo), ESTO OCURRE /SUCEDE ( es la medida de la respuesta no respuesta)

**Comment by sebasarangom** [comment]
Se cierra al terminar el sprint 1.
