### ISSUE TITLE
Calcular tiempos de Ruta

### ISSUE THREAD

**Issue by Helena-Pat29** [sebasarangom/ccpArquitecturasAgiles#7]
Como conductor del camión, cuando seleccione la opción de registrar hora de llegada donde un cliente desde la app móvil, dado que el sistema opera normalmente, quiero ver que la información de los tiempos de la ruta han sido actualizados correctamente para poder informar el sistema central del avance de la ruta. Los tiempo de ruta deben ser calculados de manera precisa para 9 de cada 10 peticiones.

**Comment by japereza** [comment]
ok

**Comment by sebasarangom** [comment]
Se cierra al terminar el sprint 1.
