### ISSUE TITLE
Seguimiento a entregas en tiempo real

### ISSUE THREAD

**Issue by ctovarb** [sebasarangom/ccpArquitecturasAgiles#8]
Como operador de logistica, cuando realice seguimientos a las entregas en curso dado que el sistema opera normalmente quiero tener un 99% de disponibilidad de las actualizaciones y notificaciones en tiempo real para alimentar tableros de control con la información de entrega tal como está sucediendo.

**Comment by japereza** [comment]
La redaccion es confusa: COMO... CUANDO.. DADO... ESPERO (Esto es la respuesta al estimulo), ESTO OCURRE /SUCEDE ( es la medida de la respuesta no respuesta)

**Comment by sebasarangom** [comment]
Se cierra al terminar el sprint 1.
