### ISSUE TITLE
Interactuar con entidades financieras

### ISSUE THREAD

**Issue by ctovarb** [sebasarangom/ccpArquitecturasAgiles#9]
Como cliente, cuando realice compras de productos dado que el sistema opera normalmente quiero poder interactuar con entidades financieras para realizar transacciones comerciales de forma segura. Esta funcionalidad debe estar disponible el 99.9% del tiempo

**Comment by japereza** [comment]
Bien redactada: es claro que es la respuesta y la medida de la respuesta

**Comment by sebasarangom** [comment]
Se cierra al terminar el sprint 1.
